version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: amazon-web-crawler
    ports:
      - "6379:6379"      # Redis port
      - "8001:8001"      # RedisInsight UI port
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3


# docker volume rm redis-data              # Manually delete volume
# # OR
# docker-compose down -v                   # Remove containers AND volumes
# # OR  
# docker-compose down --volumes            # Same as above
